### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by SentientVirtualFire** [Coding-Cactus/Cactus-Bot#8]
As it gets higher divide the units
m
km
ls
lm

**Comment by Coding-Cactus** [comment]
done!
https://github.com/Coding-Cactus/Cactus-Bot/commit/f163d33fdbfd920d016252c2b0b0e928e572e706
https://github.com/Coding-Cactus/Cactus-Bot/commit/204be7f4c0d3ef79eaf418c0c7624b8882896d01
